service: import-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action: "s3:ListBucket"
          Resource:
            - "arn:aws:s3:::alfiia-import-service-bucket"
        - Effect: "Allow"
          Action: "s3:*"
          Resource:
            - "arn:aws:s3:::alfiia-import-service-bucket/*"
        - Effect: "Allow"
          Action: "sqs:SendMessage"
          Resource: "arn:aws:sqs:eu-west-1:562467770486:catalogItemsQueue"

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: 'npm'

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http:
          path: import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true
  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: alfiia-import-service-bucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
