service: import-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1

  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::alfiia-import-service-bucket"
    - Effect: "Allow"
      Action: "s3:*"
      Resource:
        - "arn:aws:s3:::alfiia-import-service-bucket/*"

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http:
          path: import
          method: get uploaded
          cors: true